name: deploy
on:
  release:
    types: [published]

permissions:
  contents: read
  pull-requests: read

jobs:
  run-pipeline:
    name: run-pipeline
    uses: ./.github/workflows/pipeline.yml

  deploy:
    name: deploy
    runs-on: self-hosted
    needs: run-pipeline
    steps:
      - name: Connect to server
        run: ssh root@ineersa.com
      - name: Go to working directory
        run: cd /var/www/blog.ineersa.com
      - name: Git pull
        run: git pull
      - name: Build app
        run: make build-all
      - name: Restart service
        run: systemctl restart blog.service
      - name: Check status
        run: systemctl status blog.service