name: deploy
on:
  release:
    types: [published]

permissions:
  contents: read
  pull-requests: read

jobs:
  run-pipeline:
    name: run-pipeline
    uses: ./.github/workflows/pipeline.yml

  deploy:
    name: deploy
    runs-on: self-hosted
    needs: run-pipeline
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          script: |
            cd /var/www/blog.ineersa.com && git pull
            make build-all
            systemctl restart blog.service
            systemctl status blog.service