name: deploy
on:
  release:
    types: [published]
  push:
    branches:
      - main
      - master

permissions:
  contents: read
  pull-requests: read

jobs:
  run-pipeline:
    name: run-pipeline
    uses: ./.github/workflows/pipeline.yml

  deploy:
    name: deploy
    runs-on: self-hosted
    needs: run-pipeline

    steps:
      - name: Configure SSH
        run: |
          cat >>~/.ssh/config <<END
          Host blog_prod
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/id_rsa.pub
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.USERNAME }}
          SSH_HOST: ${{ secrets.HOST }}
      - name: Go to working directory and pull
        run: ssh blog_prod 'cd /var/www/blog.ineersa.com && git pull'
      - name: Build app
        run: ssh blog_prod 'cd /var/www/blog.ineersa.com && make build-all'
      - name: Restart service
        run: ssh blog_prod 'systemctl restart blog.service'
      - name: Check status
        run: ssh blog_prod 'systemctl status blog.service'