name: pipeline
on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read

jobs:
  checkout:
    name: checkout
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

  setup-go:
    name: setup-go
    runs-on: self-hosted
    needs: checkout

    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - run: go version


  generate-templ-code:
    name: generate-templ-code
    runs-on: self-hosted
    needs: [checkout, setup-go]

    steps:
      - name: Generate templ code
        uses: capthiron/templ-generator-action@v1
        with:
          commit: "false"

  golangci:
    name: lint
    runs-on: self-hosted
    needs: [checkout, setup-go, generate-templ-code]

    steps:
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
